from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class EventType(str, Enum):
    event = "Event"
    intervention = "Intervention"
    symptom = "Symptom"
    decision = "Decision"
    diary = "Diary"


class EventMeta(BaseModel):
    version: int = 1


class EventIn(BaseModel):
    id: str = Field(..., description="UUID v4 generated by client")
    client_timestamp: str = Field(..., description="ISO 8601 UTC timestamp with Z")
    type: EventType
    text: str
    metrics: dict[str, Any] = Field(default_factory=dict)
    meta: EventMeta = Field(default_factory=EventMeta)


class EventStored(EventIn):
    received_at: str = Field(..., description="ISO 8601 UTC timestamp with Z, set by server")


class QueryIn(BaseModel):
    question: str


class QueryOut(BaseModel):
    answer: str
